server:
  port: 8003
#  context-path 项目API前缀 加了要放访问的话 必须要加上这个前缀
  servlet:
    context-path: "/batch"



spring:
  datasource:
    username: bilibili
    password: 123456
    url: jdbc:mysql://localhost:3306/bilibili-batch?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  #  用于外键
  application:
    name: batch-service

mybatis:
  #让mybatis知道xml文件在哪
  mapper-locations: classpath:/mapper/**/*.xml

# PageHelper 分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql


#log4j使用时候 打印sql信息
logging:
  level:
    com:
      jkbilibili:
        mapper:
          trace
